### ISSUE TITLE
possible to include all (page-ref.) FootNotes combined?

### ISSUE THREAD

**Issue by xerc** [AOEpeople/happy_feet#17]
ref. https://github.com/connecta-ag/t3footnotes#implement-t3footnotes-plugin-in-all-templates-you-need
and https://github.com/connecta-ag/t3footnotes/blob/master/Configuration/TypoScript/setup.ts#L34-L38 << prefered

**Comment by TomSchenk** [comment]
Hi @xerc,
is this still relevant?
If yes, can you please provide more information or even a pull request?

**Comment by xerc** [comment]
yes ; how to show all foot-notes (on one page)

**Comment by tlayh** [comment]
That would be a new feature for us. We currently have no use for it, so I guess we won't do it in the near future. But if you do it yourself and create a merge request, we can put it in.

**Comment by tlayh** [comment]
Close because of no further response
