### ISSUE TITLE
typo3 12/13?

### ISSUE THREAD

**Issue by joka123** [AOEpeople/happy_feet#22]
are there plans for an update to typo3 12/13

**Comment by TomSchenk** [comment]
yes, but this will take some time. We are currently working on the v12 update. ETA ~3 months
Feel free to provide a pull request, in the meantime :-)

**Comment by aoekrz** [comment]
@joka123 

Here we go with [v12](https://github.com/AOEpeople/happy_feet/releases/tag/12.0.0)

Feel free to check it out and please report any issues!
